In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm

### 把不要的欄位刪掉，改欄位名稱，改column type，把沒有label的資料刪掉

In [2]:
restaurant_train = pd.read_csv("dataset/restaurant_train.csv", encoding="utf-8")
#刪掉不要的欄位
restaurant_train = restaurant_train.drop(columns=['aspectTerms/aspectTerm/0/_from','aspectTerms/aspectTerm/0/_to',
                                                  'aspectTerms/aspectTerm/1/_from','aspectTerms/aspectTerm/1/_to',
                                                  'aspectTerms/aspectTerm/2/_from','aspectTerms/aspectTerm/2/_to',
                                                  'aspectTerms/aspectTerm/3/_from','aspectTerms/aspectTerm/3/_to',
                                                  'aspectTerms/aspectTerm/4/_from','aspectTerms/aspectTerm/4/_to',
                                                  'aspectTerms/aspectTerm/5/_from','aspectTerms/aspectTerm/5/_to',
                                                  'aspectTerms/aspectTerm/6/_from','aspectTerms/aspectTerm/6/_to',
                                                  'aspectTerms/aspectTerm/7/_from','aspectTerms/aspectTerm/7/_to',
                                                  'aspectTerms/aspectTerm/8/_from','aspectTerms/aspectTerm/8/_to',
                                                  'aspectCategories/aspectCategory/0/_category',
                                                  'aspectCategories/aspectCategory/0/_polarity',
                                                  'aspectCategories/aspectCategory/1/_category',
                                                  'aspectCategories/aspectCategory/1/_polarity',
                                                  'aspectCategories/aspectCategory/2/_category',
                                                  'aspectCategories/aspectCategory/2/_polarity',
                                                  'aspectCategories/aspectCategory/3/_category',
                                                  'aspectCategories/aspectCategory/3/_polarity','_id'])
#把欄位重新命名
restaurant_train = restaurant_train.rename(columns={'aspectTerms/aspectTerm/0/_term': 'aspect_0', 'aspectTerms/aspectTerm/0/_polarity': 'polarity_0',
                                                    'aspectTerms/aspectTerm/1/_term': 'aspect_1', 'aspectTerms/aspectTerm/1/_polarity': 'polarity_1',
                                                    'aspectTerms/aspectTerm/2/_term': 'aspect_2', 'aspectTerms/aspectTerm/2/_polarity': 'polarity_2',
                                                    'aspectTerms/aspectTerm/3/_term': 'aspect_3', 'aspectTerms/aspectTerm/3/_polarity': 'polarity_3',
                                                    'aspectTerms/aspectTerm/4/_term': 'aspect_4', 'aspectTerms/aspectTerm/4/_polarity': 'polarity_4',
                                                    'aspectTerms/aspectTerm/5/_term': 'aspect_5', 'aspectTerms/aspectTerm/5/_polarity': 'polarity_5',
                                                    'aspectTerms/aspectTerm/6/_term': 'aspect_6', 'aspectTerms/aspectTerm/6/_polarity': 'polarity_6',
                                                    'aspectTerms/aspectTerm/7/_term': 'aspect_7', 'aspectTerms/aspectTerm/7/_polarity': 'polarity_7',
                                                    'aspectTerms/aspectTerm/8/_term': 'aspect_8', 'aspectTerms/aspectTerm/8/_polarity': 'polarity_8'})
# 把欄位型態改成str
restaurant_train['aspect_0'] = restaurant_train['aspect_0'].astype(str)
restaurant_train['aspect_1'] = restaurant_train['aspect_1'].astype(str)
restaurant_train['aspect_2'] = restaurant_train['aspect_2'].astype(str)
restaurant_train['aspect_3'] = restaurant_train['aspect_3'].astype(str)
restaurant_train['aspect_4'] = restaurant_train['aspect_4'].astype(str)
restaurant_train['aspect_5'] = restaurant_train['aspect_5'].astype(str)
restaurant_train['aspect_6'] = restaurant_train['aspect_6'].astype(str)
restaurant_train['aspect_7'] = restaurant_train['aspect_7'].astype(str)
restaurant_train['aspect_8'] = restaurant_train['aspect_8'].astype(str)

restaurant_train['polarity_0'] = restaurant_train['polarity_0'].astype(str)
restaurant_train['polarity_1'] = restaurant_train['polarity_1'].astype(str)
restaurant_train['polarity_2'] = restaurant_train['polarity_2'].astype(str)
restaurant_train['polarity_3'] = restaurant_train['polarity_3'].astype(str)
restaurant_train['polarity_4'] = restaurant_train['polarity_4'].astype(str)
restaurant_train['polarity_5'] = restaurant_train['polarity_5'].astype(str)
restaurant_train['polarity_6'] = restaurant_train['polarity_6'].astype(str)
restaurant_train['polarity_7'] = restaurant_train['polarity_7'].astype(str)
restaurant_train['polarity_8'] = restaurant_train['polarity_8'].astype(str)

restaurant_train=restaurant_train.drop(restaurant_train[restaurant_train['aspect_0']=='nan'].index) #把沒有Label的資料刪掉
restaurant_train = restaurant_train.reset_index(drop=True)
print('有label的筆數:',len(restaurant_train))
restaurant_train.head()

有label的筆數: 2021

,text,aspect_0,polarity_0,aspect_1,polarity_1,aspect_2,polarity_2,aspect_3,polarity_3,aspect_4,polarity_4,aspect_5,polarity_5,aspect_6,polarity_6,aspect_7,polarity_7,aspect_8,polarity_8,aspect count
0,But the staff was so horrible to us.,staff,negative,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,N/A
1,"To be completely fair, the only redeeming fact...",food,positive,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,N/A
2,"The food is uniformly exceptional, with a very...",food,positive,kitchen,positive,menu,neutral,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,N/A
3,"Not only was the food outstanding, but the lit...",food,positive,perks,positive,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,N/A
4,Our agreed favorite is the orrechiete with sau...,orrechiete with sausage and chicken,positive,waiters,positive,meats,neutral,dish,neutral,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,N/A

### 看每筆資料的apsect數各有多少筆資料

In [3]:
restaurant_copy = restaurant_train

aspect_9 = restaurant_copy[restaurant_copy['aspect_8'] != 'nan']
restaurant_copy = restaurant_copy.drop(restaurant_copy[restaurant_copy['aspect_8'] != 'nan'].index)

aspect_8 = restaurant_copy[restaurant_copy['aspect_7'] != 'nan']
restaurant_copy = restaurant_copy.drop(restaurant_copy[restaurant_copy['aspect_7'] != 'nan'].index)

aspect_7 = restaurant_copy[restaurant_copy['aspect_6'] != 'nan']
restaurant_copy = restaurant_copy.drop(restaurant_copy[restaurant_copy['aspect_6'] != 'nan'].index)

aspect_6 = restaurant_copy[restaurant_copy['aspect_5'] != 'nan']
restaurant_copy = restaurant_copy.drop(restaurant_copy[restaurant_copy['aspect_5'] != 'nan'].index)

aspect_5 = restaurant_copy[restaurant_copy['aspect_4'] != 'nan']
restaurant_copy = restaurant_copy.drop(restaurant_copy[restaurant_copy['aspect_4'] != 'nan'].index)

aspect_4 = restaurant_copy[restaurant_copy['aspect_3'] != 'nan']
restaurant_copy = restaurant_copy.drop(restaurant_copy[restaurant_copy['aspect_3'] != 'nan'].index)

aspect_3 = restaurant_copy[restaurant_copy['aspect_2'] != 'nan']
restaurant_copy = restaurant_copy.drop(restaurant_copy[restaurant_copy['aspect_2'] != 'nan'].index)

aspect_2 = restaurant_copy[restaurant_copy['aspect_1'] != 'nan']
restaurant_copy = restaurant_copy.drop(restaurant_copy[restaurant_copy['aspect_1'] != 'nan'].index)

aspect_1 = restaurant_copy

print('所有資料數:',len(restaurant_train))
print('1個aspect的資料數:',len(aspect_1))
print('2個aspect的資料數:',len(aspect_2))
print('3個aspect的資料數:',len(aspect_3))
print('4個aspect的資料數:',len(aspect_4))
print('5個aspect的資料數:',len(aspect_5))
print('6個aspect的資料數:',len(aspect_6))
print('7個aspect的資料數:',len(aspect_7))
print('8個aspect的資料數:',len(aspect_8))
print('9個aspect的資料數:',len(aspect_9))

所有資料數: 2021
1個aspect的資料數: 1023
2個aspect的資料數: 572
3個aspect的資料數: 269
4個aspect的資料數: 104
5個aspect的資料數: 29
6個aspect的資料數: 15
7個aspect的資料數: 5
8個aspect的資料數: 3
9個aspect的資料數: 1

### 把每筆資料對每個aspect切開，讓一筆資料只能有一個aspect，如果一筆資料有多個aspect，重複text形成一對多的格式

In [4]:
# 創一個空的dataframe
restaurant_train_1 = pd.DataFrame(columns=['text','aspect','polarity'])

# 把每筆資料的text 對 aspect terms 分開成 一個text對一個aspect、polarity
for i in tqdm(range(len(restaurant_train))):
    count = 0
    target_a = restaurant_train.loc[i,'aspect_0'] # aspect_0值
    target_p = restaurant_train.loc[i,'polarity_0'] # polarity_0的值
    while((count<=8) and (target_a != 'nan')): #如果count<=12 (因為dataframe只有0-12個aspect) 且 目標aspect值不是'nan'
        pd_temp = pd.DataFrame([[restaurant_train.loc[i,'text'], target_a, target_p]],
                              columns=['text','aspect','polarity']) # 將text、aspect、polarity變成dataframe格式
        restaurant_train_1 = restaurant_train_1.append(pd_temp, ignore_index=True) # 將dataframe加在下面
        count += 1
        if count>8: # 判斷aspect數是否有超過資料集裡的aspect數，如果超過就break
            break
        a = 'aspect_'+ str(count) #目標放在下一個aspect column name
        p = 'polarity_'+str(count) # 下一個 polarity column name
        target_a = restaurant_train.loc[i,a] # 下一個aspect 值
        target_p = restaurant_train.loc[i,p] # 下一個polarity 值
    restaurant_train.loc[i,'aspect count'] = str(count)
restaurant_train_1

100%|██████████| 2021/2021 [00:05<00:00, 394.67it/s]

,text,aspect,polarity
0,But the staff was so horrible to us.,staff,negative
1,"To be completely fair, the only redeeming fact...",food,positive
2,"The food is uniformly exceptional, with a very...",food,positive
3,"The food is uniformly exceptional, with a very...",kitchen,positive
4,"The food is uniformly exceptional, with a very...",menu,neutral
...,...,...,...
3688,Each table has a pot of boiling water sunken i...,pot of boiling water,neutral
3689,Each table has a pot of boiling water sunken i...,meats,neutral
3690,Each table has a pot of boiling water sunken i...,vegetables,neutral
3691,Each table has a pot of boiling water sunken i...,rice,neutral
3692,Each table has a pot of boiling water sunken i...,glass noodles,neutral

In [5]:
# 看分開aspect term資料筆數有沒有一樣多
print('切成單一資料筆數:',len(restaurant_train_1))
print('每個aspect相加:',len(aspect_1)+len(aspect_2)*2+len(aspect_3)*3+len(aspect_4)*4+len(aspect_5)*5+
      len(aspect_6)*6+len(aspect_7)*7+len(aspect_8)*8+len(aspect_9)*9)

切成單一資料筆數: 3693
每個aspect相加: 3693

In [6]:
# 把polarity是conflict的資料刪除，(因為conflict資料量太少)
restaurant_train_1=restaurant_train_1.drop(restaurant_train_1[restaurant_train_1['polarity']=='conflict'].index)
print('扣掉label為conflict的資料數:',len(restaurant_train_1))
restaurant_train_1

扣掉label為conflict的資料數: 3602

,text,aspect,polarity
0,But the staff was so horrible to us.,staff,negative
1,"To be completely fair, the only redeeming fact...",food,positive
2,"The food is uniformly exceptional, with a very...",food,positive
3,"The food is uniformly exceptional, with a very...",kitchen,positive
4,"The food is uniformly exceptional, with a very...",menu,neutral
...,...,...,...
3688,Each table has a pot of boiling water sunken i...,pot of boiling water,neutral
3689,Each table has a pot of boiling water sunken i...,meats,neutral
3690,Each table has a pot of boiling water sunken i...,vegetables,neutral
3691,Each table has a pot of boiling water sunken i...,rice,neutral
3692,Each table has a pot of boiling water sunken i...,glass noodles,neutral

In [8]:
restaurant_train_1 = restaurant_train_1.reset_index(drop=True)
restaurant_train_1.to_csv('restaurant_train_processed.csv',index=0)